export PATH := /home/shay/a/ece270/bin:$(PATH)
export LD_LIBRARY_PATH := /home/shay/a/ece270/lib:$(LD_LIBRARY_PATH)

YOSYS=yosys
NEXTPNR=nextpnr-ice40
SHELL=bash

PROJ	= lab10
PINMAP 	= pinmap.pcf
TCLPREF = addwave.gtkw
SRC	    = top.sv
ICE   	= ice40hx8k.sv
CHK 	= check.bin
DEM 	= demo.bin
JSON    = ll.json
SUP     = support/moddefs.sv
UART	= uart/uart.v uart/uart_tx.v uart/uart_rx.v
FILES   = $(ICE) $(SRC) $(UART)
TRACE	= $(PROJ).vcd
BUILD   = ./build

DEVICE  = 8k
TIMEDEV = hx8k
FOOTPRINT = ct256

all: cram

#########################
# Flash to FPGA
$(BUILD)/$(PROJ).json : $(ICE) $(SRC) $(PINMAP) Makefile
	# lint with Verilator
	verilator --lint-only --top-module top $(SRC) $(SUP)
	# if build folder doesn't exist, create it
	mkdir -p $(BUILD)
	# synthesize using Yosys
	$(YOSYS) -p "read_json $(JSON); read_verilog -sv -noblackbox $(FILES); synth_ice40 -top ice40hx8k -json $(BUILD)/$(PROJ).json"

$(BUILD)/$(PROJ).asc : $(BUILD)/$(PROJ).json
	# Place and route using nextpnr
	$(NEXTPNR) --hx8k --package ct256 --pcf $(PINMAP) --asc $(BUILD)/$(PROJ).asc --json $(BUILD)/$(PROJ).json 2> >(sed -e 's/^.* 0 errors$$//' -e '/^Info:/d' -e '/^[ ]*$$/d' 1>&2)

$(BUILD)/$(PROJ).bin : $(BUILD)/$(PROJ).asc
	# Convert to bitstream using IcePack
	icepack $(BUILD)/$(PROJ).asc $(BUILD)/$(PROJ).bin

#########################
# Verification Suite
VFLAGS = --build --cc --exe --trace-fst --Mdir build

verify_fa: top.sv tb_prelab.cpp
	@echo ========================================
	@echo Compiling and verifying fa...
	yosys -p "read_verilog -sv top.sv; synth_ice40 -top fa" || (echo "Failed to synthesize fa"; exit 1)
	@rm -rf build
	verilator $(VFLAGS) --top-module fa -CFLAGS -DFA top.sv tb_prelab.cpp 1>/dev/null
	./build/Vfa

verify_fa4: top.sv tb_prelab.cpp
	@echo ========================================
	@echo Compiling and verifying fa4...
	yosys -p "read_verilog -sv top.sv; synth_ice40 -top fa4" || (echo "Failed to synthesize fa4"; exit 1)
	@rm -rf build
	verilator $(VFLAGS) --top-module fa4 -CFLAGS -DFA4 top.sv tb_prelab.cpp 1>/dev/null
	./build/Vfa4

verify_bcdadd1: top.sv tb_prelab.cpp
	@echo ========================================
	@echo Compiling and verifying bcdadd1...
	yosys -p "read_verilog -sv top.sv; synth_ice40 -top bcdadd1" || (echo "Failed to synthesize bcdadd1"; exit 1)
	@rm -rf build
	verilator $(VFLAGS) --top-module bcdadd1 -CFLAGS -DBCDADD1 top.sv tb_prelab.cpp 1>/dev/null
	./build/Vbcdadd1

verify_bcdadd4: top.sv tb_prelab.cpp
	@echo ========================================
	@echo Compiling and verifying bcdadd4...
	yosys -p "read_verilog -sv top.sv; synth_ice40 -top bcdadd4" || (echo "Failed to synthesize bcdadd4"; exit 1)
	@rm -rf build
	verilator $(VFLAGS) --top-module bcdadd4 -CFLAGS -DBCDADD4 top.sv tb_prelab.cpp 1>/dev/null
	./build/Vbcdadd4

verify_bcd9comp1: top.sv tb_prelab.cpp
	@echo ========================================
	@echo Compiling and verifying bcd9comp1...
	yosys -p "read_verilog -sv top.sv; synth_ice40 -top bcd9comp1" || (echo "Failed to synthesize bcd9comp1"; exit 1)
	@rm -rf build
	verilator $(VFLAGS) --top-module bcd9comp1 -CFLAGS -DBCD9COMP1 top.sv tb_prelab.cpp 1>/dev/null
	./build/Vbcd9comp1

verify_bcdaddsub4: top.sv tb_prelab.cpp
	@echo ========================================
	@echo Compiling and verifying bcdaddsub4...
	yosys -p "read_verilog -sv top.sv; synth_ice40 -top bcdaddsub4" || (echo "Failed to synthesize bcdaddsub4"; exit 1)
	@rm -rf build
	verilator $(VFLAGS) --top-module bcdaddsub4 -CFLAGS -DBCDADDSUB4 top.sv tb_prelab.cpp 1>/dev/null
	./build/Vbcdaddsub4

verify_prelab: verify_fa verify_fa4 verify_bcd9comp1 verify_bcdadd1 verify_bcdadd4 verify_bcdaddsub4

verify_ll_alu: top.sv tb.cpp
	verilator --lint-only -Wno-MULTITOP top.sv
	yosys -p "read_verilog -sv top.sv; synth_ice40 -top ll_alu" || (echo "Failed to synthesize ll_alu"; exit 1)
	@echo ========================================
	@echo Compiling and verifying ll_alu...
	@rm -rf build
	verilator $(VFLAGS) --top-module ll_alu -CFLAGS -DLL_ALU top.sv tb.cpp 1>/dev/null
	./build/Vll_alu

verify_ll_memory: top.sv tb.cpp
	verilator --lint-only -Wno-MULTITOP top.sv
	yosys -p "read_verilog -sv top.sv; synth_ice40 -top ll_memory" || (echo "Failed to synthesize ll_memory"; exit 1)
	@echo ========================================
	@echo Compiling and verifying ll_memory...
	@rm -rf build
	verilator $(VFLAGS) --top-module ll_memory -CFLAGS -DLL_MEMORY top.sv tb.cpp 1>/dev/null
	./build/Vll_memory

verify_ll_control: top.sv tb.cpp
	verilator --lint-only -Wno-MULTITOP top.sv
	yosys -p "read_verilog -sv top.sv; synth_ice40 -top ll_control" || (echo "Failed to synthesize ll_control"; exit 1)
	@echo ========================================
	@echo Compiling and verifying ll_control...
	@rm -rf build
	verilator $(VFLAGS) --top-module ll_control -CFLAGS -DLL_CONTROL top.sv tb.cpp 1>/dev/null
	./build/Vll_control
	
#########################
# ice40 Specific Targets
check: $(CHK)
	iceprog -S $(CHK)
	
demo:  $(DEM)
	iceprog -S $(DEM)

flash: $(BUILD)/$(PROJ).bin
	iceprog $(BUILD)/$(PROJ).bin

cram: $(BUILD)/$(PROJ).bin
	iceprog -S $(BUILD)/$(PROJ).bin

time: $(BUILD)/$(PROJ).asc
	icetime -p $(PINMAP) -P $(FOOTPRINT) -d $(TIMEDEV) $<

#########################
# Clean Up
clean:
	rm -rf build/ *.fst verilog.log
